name: Docker
on:
  push:
    branches: [ "development" ]
  
jobs:
  publish_image:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: microsoft/variable-substitution@v1
        with:
          files: '${{ github.workspace }}/API/appsettings.json'
        env:
          App.Settings.ConnectionString: ${{ secrets.CONNECTION_STRING }}
          App.Settings.Jwt.Secret: ${{ secrets.JWT_SECRET }}
          Serilog.WriteTo.Args.apiKey: ${{ secrets.SEQ_API_KEY }}

      - name: build
        run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          docker build . -t brunovbs/$REPO_NAME-dev:latest

      - name: publish
        run: |
          docker login -u brunovbs -p ${{ secrets.DOCKER_HUB_TOKEN }}
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          docker push brunovbs/$REPO_NAME-dev:latest